### ISSUE TITLE
Add explaining functionality to Step class

### ISSUE THREAD

**Issue by erik-whiting** [erik-whiting/LuluTest#20]
Users can create `Step` objects and send them to a `do` method, which iterates through all the steps and performs theme in order. This is designed to save lines of code. An example is as follows:
```python
# Assume we've declared a Page object named pageObject
# Assume we've declared two BaseElement objects named input_element and this_button
steps = [
  step.Step("type", input_element, "This data"),
  step.Step("click", this_button)
]
pageObject.do(steps)
```
And the system will type "This data" in the `pageObject`'s `input_element` and then click a button, defined by the `BaseElement` instance `this_button`.

In the spirit of allowing users to have a transparent and well documented system, I would like to add a method in the `Step` class that explains itself. For example:
```python
# Assume we've declared a Page object named pageObject
>>> input_element = pageObject.element_by("id", "username")
>>> step_1 = step.Step("type", input_element, "This data")
>>> step_1.explain()
This step types "This data" into an input element of id "username"
```

Please let me know if you have any questions!

**Comment by alwinaind** [comment]
Hi I would like to take up this issue. I cannot find any property in BaseElement which captures the type of element, such as if it is <div>, <a>, etc.

**Comment by erik-whiting** [comment]
@alwinaind good morning. That would be a very helpful feature if you decide to add it. I left a comment on your pull request asking for a test. Thank you for contributing!
