### ISSUE TITLE
Add instructions for installing browser drivers in SETUP.md

### ISSUE THREAD

**Issue by wangonya** [erik-whiting/LuluTest#21]
The setup docs don't cover installing web drivers required by selenium. 

For example, following the instructions as they are and running the tests without having the chrome driver installed fails with the error: `WebDriverException: Message: 'chromedriver' executable needs to be available in the path.`

This may not be an issue for contributors who have worked with selenium before as they may already have the drivers installed, but it may cause problems for contributors new to selenium (or just beginners in general). The error is clear and it's easy enough to look for instructions online on how to install the required drivers, but I think it'd be better to just cover it in the setup docs. Makes it easier for beginners 🙂

**Comment by FarhiaM** [comment]
Hi, I would like to work on this issue it its available :)
