### ISSUE TITLE
Address codeclimate issues

### ISSUE THREAD

**Issue by erik-whiting** [erik-whiting/LuluTest#32]
Recently, codeclimate checks were implemented into LuluTest and naturally, it identified a lot of issues. Codeclimate is a static code analysis tool that identifies areas in which best practices are ignored, code smells, and other things. In order to maximize velocity, it is important that code quality be as high as possible. This issue refers to addressing the issues most recently identified by the initial analysis.

**Comment by FarhiaM** [comment]
Hi Erik! I can start going through some of them. I will be using my previous PR as reference to find code issues: https://codeclimate.com/github/erik-whiting/LuluTest/pull/31#

Let me know if there another way to find these code issues

**Comment by erik-whiting** [comment]
Hi @FarhiaM, I actually fixed the majority of these issues already and should probably close this issue.

That said, there doesn't need to be an issue for you to contribute to the project. If you want to add something or see something that could be done better, feel free to address it! Everyone's welcome to every part of the project :)

**Comment by FarhiaM** [comment]
Okay! Thanks for getting back to me :)
