### ISSUE TITLE
Better Exception classes

### ISSUE THREAD

**Issue by erik-whiting** [erik-whiting/LuluTest#52]
Right now, the custom Exception classes are not very helpful outside of their names. It would be cool if the messages could be more informative. Also, there are probably some Exception classes that haven't yet been made that should be.

**Comment by wangonya** [comment]
Hey @erik-whiting, mind giving some more info on this? Maybe an example of what is required. Might pick it up.

**Comment by erik-whiting** [comment]
Good morning @wangonya thanks for checking in. I don't have an example to give because I'm not too familiar with Python exception handling. If you look at `lulu_exceptions/LuluExceptions.py`, you'll see the existing custom exceptions are nothing more than empty classes. Making exceptions  that give the user more info (like an exception message) would be appreciated.

One example is in `action/page_actions.py`, the private method `__check_page_load` (line 33 at the moment) throws a custom exception if the `page_loaded` attribute of the `PageActions` class. The error message is in this method, it would be better if the error method was recorded in the exception class definition rather than in `page_actions`. Again, I'm not familiar with Python exception handling so I don't know if that's possible.

Also note, the project structure has changed considerably since you last worked on it. Let me know if you like the new architecture.

**Comment by wangonya** [comment]
I'll have a look 🙂

**Comment by wangonya** [comment]
Hey, so I did some reading on custom exceptions in python and found that the way the code currently is is actually the right way to do it. The classes shouldn't have anything, unless you want to override some of the behaviour of the inherited base `Exception` class from python. This short video shows what I mean: https://www.youtube.com/watch?v=hLLaw9BI-EE
I don't know, maybe I'm missing something?

**Comment by erik-whiting** [comment]
@wangonya cool thanks for taking a look. If you say it's good the way it is, then it is. Thanks again, I'll close this issue.

**Comment by wangonya** [comment]
I'm always taking a look at the project in my free time. I'll be sure to open an issue if I find that there's a better way to do it.
