### ISSUE TITLE
Make Package-able

### ISSUE THREAD

**Issue by erik-whiting** [erik-whiting/LuluTest#65]
I want to publish this to PyPI but I cannot figure out how to package it. I tried following along with the package tutorial here: https://packaging.python.org/tutorials/packaging-projects/
but I get errors. I do not have the most firm grasp of Python packaging so I'm not sure why I get the errors I get. Help is desperately needed and greatly appreciated.

**Comment by wangonya** [comment]
What errors are you getting?

Are you using the same `setup.py` file that is currently on the development branch or have you made some changes?

**Comment by wangonya** [comment]
I was able to package successfully with this setup file (only line 1 and 5 have changed):

```
from setuptools import setup, find_packages

setup(
    name='LuluTest',
    packages=find_packages(),
    version='0.1',
    license='apache-2.0',
    description='A suite of tools to un-complicate browser automation',
    author='Erik Whiting',
    author_email='erik@erikwhiting.com',
    url='https://github.com/erik-whiting/LuluTest',
    keywords=['testing', 'browser automation', 'webdriver'],
    install_requires=[
        'selenium',
        'urllib3',
        'pyyaml'
    ],
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Testing',
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
    ],
)
```

I didn't make any other change. Sorry I can't open a PR for this at the moment. Let me know if it works for you.

You might also need to `pip install wheel` then run `python setup.py sdist bdist_wheel` to package.

**Comment by erik-whiting** [comment]
Hey @wangonya thanks for messing around with this. Yeah I have been playing around with it and I'm surprised you were able to get it to work. When you packaged the project, were you able to use it in the command line like any other kind of package?

**Comment by wangonya** [comment]
How do you intend it be used from the command line? I've been able to install the packaged project with pip but it's a bit unclear how to use it from the command line.

**Comment by erik-whiting** [comment]
I guess "command line" was a bad example. I ultimately intend for it to be used in other projects as a package people add to their tests. I had been writing the `smoke_test` in the command line to see if my packaging worked and hadn't had any luck until last night (the stuff in the `make-packageable` branch)

**Comment by wangonya** [comment]
Oh, if you mean being able to import it in other projects after installing it with pip then I'll need to test that. Let me upload what I've packaged to TestPypi and pip install it from there on another project. Don't worry, I'll use a random name for the project so that LuluTest isn't taken.

I'll let you know how that goes.

**Comment by wangonya** [comment]
Ok so installing works but importing seems to be the issue. It seems like the packaging exposed the internal packages only (page, action, etc) instead of the main overall package (LuluTest). LuluTest isn't accessible but I'm able to import the internal packages.

You can install my test package with `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple wangonya-llu-test ` to see the behaviour.

![Screenshot 2020-08-04 at 20 29 29](https://user-images.githubusercontent.com/19375569/89325570-ab413200-d691-11ea-951c-0683b025d7fa.png)

**Comment by wangonya** [comment]
I'll try and see if I can find a way around this.

**Comment by wangonya** [comment]
I don't know if you'll consider this option, but I've been able to get it to work by changing the folder structure a little:

```
LuluTest/
├── CONTRIBUTING.md
├── LICENSE
├── LICENSE.txt
├── LuluTestArchitecture.PNG
├── README.md
├── SETUP.md
├── requirements.txt
├── setup.cfg
├── setup.py
├── wangonya_llu_test  # rename to lulutest
│   ├── __init__.py
│   ├── action
│   ├── element
│   ├── lulu_exceptions
│   ├── page
│   ├── page_element_interface
│   ├── step
│   └── tests
```

I'm now able to package, install and use it correctly.
If you want to test it: `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple wangonya-llu-test==0.5`. Only the latest version (0.5) works.

![Screenshot 2020-08-04 at 21 50 19](https://user-images.githubusercontent.com/19375569/89332701-830b0080-d69c-11ea-8ceb-76a1364a3ec0.png)
